name: Database Sync

on:
  workflow_dispatch: # Allow manual triggering only to save minutes

jobs:
  deploy_migrations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Push Migrations to Staging
        if: github.ref == 'refs/heads/staging'
        run: |
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID_STAGING }} --password ${{ secrets.SUPABASE_DB_PASSWORD_STAGING }}
          supabase db push --password ${{ secrets.SUPABASE_DB_PASSWORD_STAGING }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Push Migrations to Production
        if: github.ref == 'refs/heads/main'
        run: |
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID_PROD }} --password ${{ secrets.SUPABASE_DB_PASSWORD_PROD }}
          supabase db push --password ${{ secrets.SUPABASE_DB_PASSWORD_PROD }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
