name: Database Sync

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy_migrations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Push Migrations to Staging
        if: github.ref == 'refs/heads/staging'
        run: supabase db push --db-url "postgresql://postgres:${{ secrets.SUPABASE_DB_PASSWORD_STAGING }}@db.${{ secrets.SUPABASE_PROJECT_ID_STAGING }}.supabase.co:5432/postgres?sslmode=verify-full"
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_IP_VERSION: 4

      - name: Push Migrations to Production
        if: github.ref == 'refs/heads/main'
        run: supabase db push --db-url "postgresql://postgres:${{ secrets.SUPABASE_DB_PASSWORD_PROD }}@db.${{ secrets.SUPABASE_PROJECT_ID_PROD }}.supabase.co:5432/postgres?sslmode=verify-full"
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_IP_VERSION: 4
